--RESERVAS CON EL DETALLE  VACIO
SELECT C.NRORESERVA,D.NRORESERVA,C.OT,C.FECHA  FROM RESERVA_CAB AS C LEFT JOIN RESERVA_DET AS  D 
ON C.NRORESERVA=D.NRORESERVA  WHERE C.ESTADO='00'
AND TIPO='ot-cc' AND  D.NRORESERVA IS NULL
ORDER BY C.NRORESERVA


UPDATE  RESERVA_CAB  SET  ESTADO='06'  WHERE  NRORESERVA='1524'