

SELECT * FROM AUD_DOCUMENTO


SELECT CANUMDOC,DECODIGO,DEDESCRI,DEUNIDAD,DECANTID,CAORDFAB FROM  
[015BDCOMUN].DBO.MOVALMCAB AS C INNER JOIN [015BDCOMUN].DBO.MOVALMDET AS D
ON C.CANUMDOC=D.DENUMDOC INNER JOIN [021BDCOMUN].DBO.RESERVA_CAB AS RC ON
C.CAORDFAB=RC.OT WHERE  CATD='NI' AND CAALMA='01'  AND DETD='NI' AND DEALMA='01'
AND CAFECDOC BETWEEN '06-05-2015' AND '31-12-2020' ORDER BY CANUMDOC






