
SELECT * FROM  [015BDCOMUN].DBO.MOVALMCAB AS C WHERE CANUMDOC='0000015454'
AND CATD='NI' AND CAALMA='01'


SELECT * FROM  [015BDCOMUN].DBO.MOVALMDET AS D WHERE DENUMDOC='0000015454'
AND DETD='NI' AND DEALMA='01'

SELECT * FROM RESERVA_DET

SELECT CANUMDOC,DEITEM,DECODIGO,DEDESCRI,DEUNIDAD,DECANTID,CAORDFAB,OT FROM  
[015BDCOMUN].DBO.MOVALMCAB AS C INNER JOIN [015BDCOMUN].DBO.MOVALMDET AS D
ON C.CANUMDOC=D.DENUMDOC INNER JOIN [021BDCOMUN].DBO.RESERVA_CAB AS RC ON
C.CAORDFAB=RC.OT WHERE CANUMDOC='0000015454'
AND CATD='NI' AND CAALMA='01'  AND DETD='NI' AND DEALMA='01'
AND CAFECDOC BETWEEN '06-05-2015' AND '31-12-2020' ORDER BY CANUMDOC



CREATE TABLE AUD_DOCUMENTO(
IDAUD_DOCUMENTO INT IDENTITY PRIMARY KEY,
CANUMDOC VARCHAR(20),
DECODIGO VARCHAR(30),
DEDESCRI NUMERIC(9,6),
DEUNIDAD VARCHAR(10),
DECANTID NUMERIC(9,6),
CAORDFAB VARCHAR(10),
)

