


--INSERTAR EN LA  RESERVA 
--CODIGO PHP
--<?php $FECHA=date('Y-d-m');//FECHA ACTUAL?>

INSERT INTO [020BDCOMUN].DBO.RESERVA_DET(NRORESERVA,CODIGO,CANTIDAD,OT,ITEM,
	DESCRIPCION,NUMERO_DOC,UNIDAD,ESTADO,REQUERIMIENTO,CANT_PEND)
SELECT '423',DECODIGO,DECANTID,CAORDFAB,DEITEM,DEDESCRI,CANUMDOC,DEUNIDAD,'00','',DECANTID 
 FROM [011BDCOMUN].DBO.MOVALMCAB  AS C  INNER JOIN 
[011BDCOMUN].DBO.MOVALMDET  AS D ON C.CANUMDOC=D.DENUMDOC
 WHERE CATD='NI' AND CAALMA='01' AND  DETD='NI' AND DEALMA='01' AND 
 DECODMOV='CL' AND DEESTADO='V'  AND CACODMOV='CL' 
AND C.CAFECDOC   BETWEEN '$FECHAACTUAL' AND '2065-12-31' 
AND CAORDFAB IN (SELECT  CODIGOOT FROM [020BDCOMUN].DBO.CENCOSOT )
AND DENUMDOC NOT IN (SELECT CANUMDOC FROM [020BDCOMUN].DBO.AUD_DOCUMENTO)
AND CANUMDOC='0000016672'
ORDER BY DENUMDOC,DEITEM

--REGISTRAR  EL NUMERO DE LA NOTA DE INGRESO
INSERT INTO [020BDCOMUN].DBO.AUD_DOCUMENTO(CANUMDOC)
SELECT  CANUMDOC
 FROM [011BDCOMUN].DBO.MOVALMCAB  AS C 
 WHERE CATD='NI' AND CAALMA='01' AND   CACODMOV='CL' 
AND C.CAFECDOC   BETWEEN '$FECHAACTUAL' AND '2065-12-31' 
AND CAORDFAB IN (SELECT  CODIGOOT FROM [020BDCOMUN].DBO.CENCOSOT )
AND CANUMDOC NOT IN (SELECT CANUMDOC FROM [020BDCOMUN].DBO.AUD_DOCUMENTO)
AND CANUMDOC='0000016672'
GROUP BY CANUMDOC
ORDER BY CANUMDOC


/*TABLA QUE  MANEJA LA AUDITORIA DE LOS DOCUMENTOS NOTA DE INGRESO
 VINCULADOS A UNA OT.
 CUANDO EL DETALLE DE LA NI ES TRANFERIDO A LA RESERVA 423, SE REGISTRA
 EL NUMERO DE DOCUMENTO EN ESTA TABLA*/

SELECT * FROM  [020BDCOMUN].DBO.AUD_DOCUMENTO



/*CUANDO  EL USUARIO TRANSFIERE EL DETALLE DE LA NOTA DE INGRESO A  SU RESERVA,
EL  NUMERO DE DOCUMENTO DE GUARDA EN ESTA TABLA*/

SELECT * FROM  [020BDCOMUN].DBO.DOCUMENTO